puppetlabs/puppet-module-gems

CHANGELOG.md, config/info.yml
Includes a minor update to the dependencies config to accommodate the basic Windows environment not being able to install/build gem dependencies with native extensions unless Ruby Devkit or equivalent is installed.
=> Release 0.0.2

config/dependencies.yml, config/info.yml
As subsequent versions up to and including the latest are causing failures on SLES.
=> [MODULES-4643] Pin to specinfra version 2.67.3

config/dependencies.yml
this adds the rspec_junit_formatter as a shared dev gem. it is compatible with both posix and windows and we're currently using it on Jenkins for all unit tests. to expand to acceptance tests and cut down on Jenkins config clutter, i'm just sticking it in the bundle.
=> (MODULES-4936) add rspec_junit_formatter

config/dependencies.yml
string_wrapper.rb exists in gettext-setup and  wraps all of the ruby strings to prepare them for translation.
=> (MODULES-5135) Adding gettext-setup

docker/Dockerfile-puppet-4, docker/Dockerfile-puppet-5, docker/Gemfile, docker/README.md
The README covers the rationale for why I think this is useful. Opening a PR mainly for visibility and easy of trying this out. Rather than having the Dockerfiles hand rolled it would be possible to just generate them from the data structure already present in the repository for instance.
I've also pushed the images to my personal repository if anyone wants to test them out. https://hub.docker.com/r/garethr/puppet-module/
That means you should just be able to run (for instance)
```
git clone https://github.com/puppetlabs/puppetlabs-image_build.git
cd puppetlabs-image_build
docker run -v `pwd`:/module -it puppet/puppet-module:5 spec
```
I've not done it yet but this should work for Beaker as well. With the Docker backend if you mount the socket, and with the other hypervisors if you pass …
=> (MAINT) Add example of using gems to build shared Docker images

config/dependencies.yml
`semantic_puppet` is a soft dependency of `metadata-json-lint`.
=> (PDK-487) Add semantic_puppet gem

config/dependencies.yml
Since we still need to support early 5.x releases which conflict with
semantic_puppet, we cannot carry this yet.
This reverts commit 0772b4510eb6f2e802b04400e251b71d114320ac.
=> Revert "(PDK-487) Add semantic_puppet gem"

config/dependencies.yml
As this is a plug in for puppet-lint it automatically runs against the
code base resulting in puppet-lint failures. In order to resolve this
the plug-in needs to be removed. It can be implemented on a per module
basis.
=> Remove puppet-lint-i18n

CHANGELOG.md, config/info.yml
This release removes `puppet-lint-i18n` dependency.
=> Release prep for 0.2.1

CHANGELOG.md, config/dependencies.yml, config/info.yml
2.2.0 was a broken release so we pinned < 2.2.0, but that is fixed now.
rubocop is still pinned at a version that has rainbow < 3.0.0.
=> Unpin rainbow

Gemfile, README.md, exe/push-gems.rb
I removed the call to push to stickler because we already mirror rubygems.org on artifactory
=> (RE-9907) Migrate from stickler to artifactory

config/dependencies.yml
If we want to encourage the use of Puppet Strings, we should include it in our standard toolset. It is currently not in puppet-module-gems but it seems like a good place for it. This change adds it to the shared dev dependency list.
=> (maint) add puppet-strings to shared dev deps

config/dependencies.yml
Rubygems should prefer the newer version anyway, but lets be specific about it.
=> (maint) Skip over parser 2.5.1.1

config/dependencies.yml
Sles 15 requires a newer version of the gem as the way in which it checks for the sles version is no longer the same.
=> (MODULES-8138) - Bump of specinfra to work with Sles 15

config/dependencies.yml
This change adds the [dependency checker](https://github.com/puppetlabs/dependency_checker) gem, allowing us to verify the impact of version bumps on our modules during pre-release. I have tested the changes against the following modules with no issues (see spoilers for adhoc results):
<details><summary>puppetlabs-accounts</summary>
</details>
<details><summary>puppetlabs-acl</summary>
</details>
<details><summary>puppetlabs-iis</summary>
</details>
<details><summary>puppetlabs-stdlib</summary>
</details>
=> (MODULES-8770) Add dependency_checker gem

config/dependencies.yml
This version bump has been added to consume changes in the most recent release of specinfra which provide fixes for SLES 11 and Solaris 11 test failures on https://github.com/puppetlabs/puppetlabs-accounts/pull/221. 
Tested out on the following modules successfully:
<details><summary>puppetlabs-accounts</summary>
</details>
<details><summary>puppetlabs-acl</summary>
</details>
<details><summary>puppetlabs-iis</summary>
</details>
<details><summary>puppetlabs-stdlib</summary>
</details>
=> (MODULES-7469) Bump specinfra to 2.77.1

config/dependencies.yml
More specific versions than before to ensure that bundler pulls in versions with needed bugfixes
=> (maint) Bump FacterDB and rspec-puppet-facts versions

config/dependencies.yml
Beaker requires net-ssh however for older ruby versions this needs to be pinned
to and old version of net-ssh.  This commit adds net-ssh to the old Ruby 2.1
gems, with a version pin.
=> (PDK-1465) Add net-ssh to ruby 2.1 for system tests

config/dependencies.yml
This is required for the upcoming `pdk console` command.
=> Adds puppet-debugger gem to list of dependencies

CHANGELOG.md, config/info.yml
See CHANGELOG for details of changes since `0.4.2`
Tested against the following modules:
- `puppetlabs-acl`
- `puppetlabs-registry`
- `puppetlabs-stdlib`
=> Release prep for v0.4.3

config/dependencies.yml
See https://github.com/ruby-concurrency/concurrent-ruby/issues/849 for details.
I've ran a survey over supported modules and no further segfaults occurred when using concurrent-ruby 1.1.5.
=> Avoid concurrent-ruby 1.1.6 which is triggering MRI segfaults

CHANGELOG.md, config/info.yml
Release prep for 0.4.4
See CHANGELOG for details of changes since 0.4.3
Testing in progress
Tested against the following modules:
Successful Release checks and travis/apveyor
https://github.com/puppetlabs/puppetlabs-motd/pull/290
https://github.com/puppetlabs/puppetlabs-reboot/pull/234
Successful Travis/appveyor
https://github.com/puppetlabs/puppetlabs-acl/pull/182
https://github.com/puppetlabs/puppetlabs-stdlib/pull/1092
Acceptance tests running successfully on release checks for and also ran locally the spec tests 2.5.3 and acceptance tests on puppet agent5.All ran clean.(Screenshots of results are attached with modules PR)
https://github.com/puppetlabs/puppetlabs-stdlib/pull/1092
Opened ticket for spec tests failures for 2.6.3 on release checks.
Acceptance tests running successfully …
=> (IAC-557) Release prep 0.4.4

.travis.yml, README.md, appveyor.yml, config/dependencies.yml
The "other cleanups" are splitting out some gems into specific version pins for the different ruby versions so that more recent versions can be used, and removing some redundant pins.
Fixes #127 ; fixes #118
=> (IAC-858) Add ruby 2.7 and other cleanups

config/dependencies.yml, config/info.yml
`simplecov` dropped support for Ruby 2.4 from version `v0.19.0` onwards:
https://github.com/simplecov-ruby/simplecov/releases/tag/v0.19.0
Closes puppetlabs/pdk-templates#345
=> (IAC-1074) Pin simplecov to '< 0.19.0' on Ruby 2.4

config/dependencies.yml
`simplecov` version `0.19.0` requires Ruby 2.5 or later:
https://github.com/simplecov-ruby/simplecov/releases/tag/v0.19.0
`simplecov` version `0.19.0` is also causing builds to hang on
TravisCI, so we should pin to `< 0.19.0` on Ruby 2.5, 2.6 & 2.7
until this is resolved.
`codecov` yanked all versions prior to `0.2.0`:
codecov/codecov-ruby#87
Pin codecov to `>= 0.2` and `< 0.2.6` (`0.2.5` is the last ver
to support all Ruby versions)
Closes puppetlabs/pdk-templates#345
Closes #138
=> (IAC-1074) Pin codecov to '~> 0.2' and simplecov to '< 0.19.0'

exe/push-gems.rb
This ensures that the gem owners list accurately reflects that
defined in the OWNERS list.
=> (IAC-1091) Remove owners from gem not within OWNERS list

config/dependencies.yml
* puppet-debugger dropped support for ruby < 2.4 in the
1.0 version. This change represents the new version by adding
to any ruby >= 2.4.  All older versions of ruby will get the
puppet-debugger gem less than 1.0.0 release.
=> Update puppet-debugger gem to 1.0 for ruby 2.4+

config/dependencies.yml
avoid breaking change until https://github.com/rodjek/rspec-puppet/pull/811 is released
=> Pin rspec-expectations

config/dependencies.yml
Pin parallel to < 1.20 on ruby 2.4, since 1.20 requires ruby 2.5  or higher. Fixes spectest run with puppet 5.5, which uses ruby 2.4
=> Pin parallel to < 1.20 on ruby 2.4, since 1.20 requires ruby 2.5 

config/dependencies.yml
Verified this version working with puppetlabs-apache unit tests. See https://github.com/mcanevet/rspec-puppet-facts/pull/122
=> Allow rspec-puppet-facts v2

config/dependencies.yml
Since https://github.com/rodjek/rspec-puppet/pull/811 has been released as part of rspec-puppet 2.8.0, we can drop this pin again.
=> Remove rspec-expectations pin

config/dependencies.yml
With the release of Puppet 7, we will soon run in to issues on our
CI pipelines for the Puppet supported modules, as bolt has quite
a narrow band of support for what version Puppet it supports.
There is no requirement for us to depend on Litmus -> Bolt for spec
test execution on Ruby 2.5 / Puppet 6 and acceptance tests can run
on any Ruby version.
This change removes Litmus as a dependency on Ruby 2.5 and 2.6 to
facilitate Puppet 5, 6 & 7 spec and acceptance test execution on the
supported modules CI pipelines.
It would be advised that the next release of this gem be a minor version
bump (i.e. `0.6`) given the significance of the change.
Tested against the [`puppetlabs-motd` module](https://github.com/puppetlabs/puppetlabs-motd/pull/357) on …
=> (IAC-1233) Remove litmus as a dependency in Ruby 2.5 & 2.6

config/dependencies.yml
The 3.0.0 release dropped rubies before 2.1, which is irrelevant to the puppet-module-gems
=> Update metadata-json-lint pin to allow 3.x release train

CHANGELOG.md, README.md, config/dependencies.yml, config/info.yml
This fixes https://github.com/puppetlabs/puppetlabs_spec_helper/pull/328#issuecomment-762320608
=> Pin down pathspec on older ruby versions; release prep for v1.0.2

config/dependencies.yml
While working on bumping the agent core modules pdk template version to
2.2.0, I noticed that when trying to use a newer beaker version I would
get the following error:
```
Bundler could not find compatible versions for gem "pry":
In Gemfile:
beaker (~> 4.29) was resolved to 4.30.0, which depends on
pry-byebug (~> 3.9) was resolved to 3.9.0, which depends on
pry (~> 0.13.0)
puppet-module-posix-dev-r2.7 (~> 1.0) was resolved to 1.1.0, which depends on
pry (~> 0.10.4)
pdk (FATAL): Unable to resolve default Gemfile dependencies.
```
This commit removes the .z form the pry dependency so the optimistic
search isn't constrained to `0.10.4`
=> (maint) Fix pry dependency issue.

exe/audit-owners.rb, exe/push-gems.rb
Following a close call with all owners nearly being removed, I've
split out the gem owner auditing / removal from the `push-gems.rb`
script and created a dedicated `audit-owners.rb` script to:
- Query the owners of each Puppet Module Gems gem
- Compare the owners of each gem to the expectation defined in OWNERS
- Generate a list of owners that should be removed
- Generate a list of owners that should be added
- Request confirmation for the add / remove operation
- Execute the add / remove operation using `gem owner`
Also have updated the `OWNERS` list
=> (MAINT) Make a safer gem ownership script
