- config/dependencies.yml
this adds ruby 2.4 sections to all platforms in dependencies.yml
> (maint) add ruby 2.4

- config/dependencies.yml
Needed for https://github.com/puppetlabs/pdk/pull/99
> (SDK-256) Add metadata-json-lint to the Windows dev gems

- CHANGELOG.md
- config/dependencies.yml
- config/info.yml
Also includes commit to remove blacksmith and cleans up version pins.
> Release Prep for 0.0.9

- config/dependencies.yml
parallel_tests is already in this project, so we don't need to add or change anything else.
> (SDK-312) Bump puppetlabs_spec_helper version

- config/dependencies.yml
Version 2.3.1 contains the spec_list_json rake task.
> (PDK-373) require fixed puppetlabs_spec_helper version

- config/dependencies.yml
There are various tests that rely on these gems. This includes the tests
ran in Travis and acceptance tests for locales.
> (maint) - Gems need to be installed for i18n Tests

- README.md
This is adding a section on how to manually test your changes to ensure nothing
has broken including the formatting of the Gemfile.
> Docs - Adding a section on how to test your changes

- config/dependencies.yml
This is in conjunction with https://github.com/puppetlabs/pdk-templates/pull/42
> (PDK-389) Removes unnecessary windows pins

- config/dependencies.yml
Required for https://github.com/puppetlabs/pdk/pull/515
> (PDK-636) Bump PSH minimum version to 2.8.0

- config/dependencies.yml
Fixes #93 once the next release goes out.
> Add build configuration for Ruby 2.6

- exe/push-gems.rb
@bmjen Would you be able to take a look at this when you have a chance? Cheers!
> (maint) Add Loredana Ionce as owner

- exe/push-gems.rb
> (maint) Update email for Glenn Sarti

- exe/push-gems.rb
> (maint) Add sheena@puppet.com to OWNERS

- config/dependencies.yml
> (MAINT) Pin i18n gem for Ruby 2.1.x

- config/dependencies.yml
* updates version from 0.14 to 0.18
> Minor version bump for puppet-debugger

- config/info.yml
This reverts commit 9e0c8976c66f42defd0579c2b507855f96f228bb.
> Revert "(IAC-1074) Bump gem version to 0.5.1"

- .gitpod.Dockerfile
- .gitpod.yml
- README.md
This adds support for developing this project in a gitpod environment.  Developers will be able to click the gitpod icon at the top of the readme for quick and easy environment setup.
> Add initial setup of gitpod config files

- exe/push-gems.rb
* pass gem name when removing owner
* fix michael and daniel's ID
* sort files by name to get predictable order of operations
> fixup push-gems script

- CHANGELOG.md
- config/info.yml
> Release-prep v0.5.3

- config/dependencies.yml
Currently releasing puppet_litmus 0.21.0 however it is blocked until this change is merged and released.
> (maint) Update dependency range

- config/dependencies.yml
This will allow the use of https://github.com/puppetlabs/puppetlabs_spec_helper/pull/332
> Allow puppetlabs_spec_helper 3.0.0

- CHANGELOG.md
- config/info.yml
* Allow puppetlabs_spec_helper 3.0.0 and later
> Release prep for v1.1.0
